name: CI Infra as Code

on:
  [workflow_dispatch, push]

concurrency: ci-${{ github.ref }}

jobs:

  lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Setup CloudFormation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Lint CloudFormation files.
        run: |
          cfn-lint --version
          cfn-lint -t cfn/*.y*ml -I

  trivy:
    name: Run Trivy (Iac and fs mode)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Trivy scans Infrastructure as Code (IaC) Terraform, CloudFormation, Dockerfile and Kubernetes.
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

  insecure-cf:
    name: Scan Insecure Cloudformation patterns
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Insecure Cloudformation patterns
        uses: stelligent/cfn_nag@master
        with:
          input_path: cfn
          extra_args: --fail-on-warnings --deny-list-path .cfnnagcfg.yml
          #extra_args: --fail-on-warnings --blacklist-path .cfnnagcfg.yml

      - name: Fail if cfn_nag scan contains failures, warnings
        # sum cfn_nag failures, warnigns and return it as exit code
        run: |
          exit `grep -E '^(Failures|Warnings)' cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`

  Checkov:
    name: Checkov - Security Analysis of Cloudformation
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cfn/
          quiet: false # optional: display only failed checks
          soft_fail: false # optional: do not return an error code if there are failed checks
          skip_check: CKV_AWS_115,CKV_AWS_116,CKV_AWS_173,CKV_AWS_260

  deploy:
    name: deploy 
    needs: [checkov,insecure-cf,trivy,lint]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the thing
        run: |
          echo Deploying ðŸš€