name: CI Infra as Code

on:
  [workflow_dispatch, push]

concurrency: ci-${{ github.ref }}

jobs:

  lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Setup CloudFormation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Lint CloudFormation files.
        run: |
          cfn-lint --version
          cfn-lint -t cfn/*.y*ml -I

  trivy:
    name: Run Trivy (Iac and fs mode)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Trivy scans Infrastructure as Code (IaC) Terraform, CloudFormation, Dockerfile and Kubernetes.
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'