name: CI Infra as Code

on:
  [workflow_dispatch, push]

concurrency: ci-${{ github.ref }}

jobs:

  lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Setup CloudFormation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Lint CloudFormation files.
        run: |
          cfn-lint --version
          cfn-lint -t cfn/*.y*ml -I
